export const permissionCatalog = [
  ['platform', 'tenant.manage', 'Manage tenants'],
  ['platform', 'billing.manage', 'Manage subscriptions and billing'],
  ['company', 'company.manage', 'Manage companies'],
  ['company', 'branch.manage', 'Manage branches'],
  ['security', 'user.manage', 'Manage users'],
  ['security', 'role.manage', 'Manage roles and permissions'],
  ['accounting', 'ledger.read', 'Read ledgers'],
  ['accounting', 'ledger.manage', 'Manage ledgers'],
  ['accounting', 'voucher.create', 'Create vouchers'],
  ['accounting', 'voucher.approve', 'Approve vouchers'],
  ['sales', 'invoice.manage', 'Manage sales invoices'],
  ['purchase', 'invoice.manage', 'Manage purchase invoices'],
  ['inventory', 'item.manage', 'Manage inventory items'],
  ['inventory', 'stock.adjust', 'Adjust stock'],
  ['gst', 'return.manage', 'Manage GST returns'],
  ['manufacturing', 'production.manage', 'Manage production'],
  ['payroll', 'payroll.manage', 'Manage payroll'],
  ['banking', 'reconciliation.manage', 'Manage bank reconciliation'],
  ['reports', 'financial.read', 'Read financial reports'],
  ['marketplace', 'addon.manage', 'Manage add-ons'],
  ['compliance', 'rule.manage', 'Manage compliance rules'],
  ['approvals', 'workflow.manage', 'Manage approval workflows'],
].map(([module, action, name]) => ({
  module,
  action,
  code: `${module}.${action}`,
  name,
}));
